FROM node:14-alpine
WORKDIR /app
COPY package*.json ./
RUN npm i
RUN npm install popper.js --save
RUN npm install @popperjs/core --save
COPY . .
# RUN npm run build
EXPOSE 8080
CMD ["npm", "run", "serve"]
