version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    container_name: frontend
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
